# fMRI data ##################################################################

training fmri:
  MT:
    - /home/kiss/data/fmri_shared/datasets/Deeprecon/fmriprep/MT_ImageNetTrainingV2_volume_native_fmap_rep3.h5

test fmri:
  MT:
    - /home/kiss/data/fmri_shared/art/MT260706/bdata/MT260706_ArtImage_volume_native_Wien2D_fmap_prep.h5

rois:
  VC:  ROI_VC = 1

# The number of voxels used in feature decoding
rois voxel num:
  VC:  500

label key:
  stimulus_name

# DNN features ###############################################################

training feature dir:
  - /home/nu/data/contents_shared/ImageNetTraining_v2/derivatives/features

#test feature dir:
#  - XXX

network:
  caffe/VGG_ILSVRC_19_layers

layers:
  - conv1_1
  - conv1_2
  - conv2_1
  - conv2_2
  - conv3_1
  - conv3_2
  - conv3_3
  - conv3_4
  - conv4_1
  - conv4_2
  - conv4_3
  - conv4_4
  - conv5_1
  - conv5_2
  - conv5_3
  - conv5_4
  - fc6
  - fc7
  - fc8

# Feature decoding ###########################################################

feature decoder dir:
  /home/nu/data/contents_shared/ImageNetTraining_v2/derivatives/feature_decoders/deeprecon_fmriprep_fmap_rep3_500voxel_allunits_fastl2lir_alpha100
# Decoded features
decoded feature dir:
  /home/nu/mmitsuoka/project/art/ted26/derivatives/decoded_features/ArtImage_Wien2D_fmap

# Learning parameters
alpha: 100
chunk axis: 1

test single trial: false

# Figure output
#decoding figure dir:
  #./data/figures/feature_decoding/ImageNetTest/deeprecon_fmriprep_pyfastl2lir_alpha100_allunits
