# CV feature decoding

decoder:
  name: deeprecon_cv_fmriprep_pyfastl2lir_alpha100_allunits
  path: ./data/feature_decoding_cv/ImageNetTraining/${decoder.name}/${decoder.features.name}
  parameters:
    alpha: 100
    chunk_axis: 1

  fmri:
    name: ImageNetTraining_fmriprep_volume_native
    subjects:
      - name: sub-01
        paths:
          - ./data/fmri/Deeprecon/sub-01_${decoder.fmri.name}.h5
      - name: sub-02
        paths:
          - ./data/fmri/Deeprecon/sub-02_${decoder.fmri.name}.h5
      - name: sub-03
        paths:
          - ./data/fmri/Deeprecon/sub-03_${decoder.fmri.name}.h5
    rois:
      - {name: V1,  select: ROI_V1 = 1,  num: 500}
      - {name: V2,  select: ROI_V2 = 1,  num: 500}
      - {name: V3,  select: ROI_V3 = 1,  num: 500}
      - {name: hV4, select: ROI_hV4 = 1, num: 500}
      - {name: LOC, select: ROI_LOC = 1, num: 500}
      - {name: FFA, select: ROI_FFA = 1, num: 500}
      - {name: PPA, select: ROI_PPA = 1, num: 500}
      - {name: LVC, select: ROI_LVC = 1, num: 500}
      - {name: HVC, select: ROI_HVC = 1, num: 500}
      - {name: VC,  select: ROI_VC = 1,  num: 500}
    label_key: stimulus_name

  features:
    name: caffe/VGG19
    paths:
      - ./data/features/ImageNetTraining/${decoder.features.name}
    layers:
      - conv1_1
      - conv1_2
      - conv2_1
      - conv2_2
      - conv3_1
      - conv3_2
      - conv3_3
      - conv3_4
      - conv4_1
      - conv4_2
      - conv4_3
      - conv4_4
      - conv5_1
      - conv5_2
      - conv5_3
      - conv5_4
      - fc6
      - fc7
      - fc8

decoded_feature:
  name: deeprecon_cv_fmriprep_pyfastl2lir_alpha100_allunits
  path: ./data/feature_decoding_cv/ImageNetTraining/${decoded_feature.name}/${decoded_feature.features.name}
  parameters:
    average_sample: true

  decoder:
    name: ${decoder.features.name}
    path: ./data/feature_decoding_cv/ImageNetTraining/${decoder.name}/${decoder.features.name}
    parameters:
      alpha: ${decoder.parameters.alpha}
      chunk_axis: ${decoder.parameters.chunk_axis}

  fmri:
    name: ImageNetTraining_fmriprep_volume_native
    subjects:
      - name: sub-01
        paths:
          - ./data/fmri/Deeprecon/sub-01_${decoded_feature.fmri.name}.h5
      - name: sub-02
        paths:
          - ./data/fmri/Deeprecon/sub-02_${decoded_feature.fmri.name}.h5
      - name: sub-03
        paths:
          - ./data/fmri/Deeprecon/sub-03_${decoded_feature.fmri.name}.h5
    rois:
      - {name: V1,  select: ROI_V1 = 1}
      - {name: V2,  select: ROI_V2 = 1}
      - {name: V3,  select: ROI_V3 = 1}
      - {name: hV4, select: ROI_hV4 = 1}
      - {name: LOC, select: ROI_LOC = 1}
      - {name: FFA, select: ROI_FFA = 1}
      - {name: PPA, select: ROI_PPA = 1}
      - {name: LVC, select: ROI_LVC = 1}
      - {name: HVC, select: ROI_HVC = 1}
      - {name: VC,  select: ROI_VC = 1}
    label_key: stimulus_name
    exclude_labels:

  features:
    name: caffe/VGG19
    paths:
      - ./data/features/ImageNetTraining/${decoded_feature.features.name}
    layers:
      - conv1_1
      - conv1_2
      - conv2_1
      - conv2_2
      - conv3_1
      - conv3_2
      - conv3_3
      - conv3_4
      - conv4_1
      - conv4_2
      - conv4_3
      - conv4_4
      - conv5_1
      - conv5_2
      - conv5_3
      - conv5_4
      - fc6
      - fc7
      - fc8

# Cross-validation setting
cv:
  # Key used to split training and test samples for cross-validation (e.g., 'Run')
  key: Run

  # Values of the key splitting training and test samples in each cross-validation fold.
  # If omitted, leave-one-out cross-validation will be performed based on values of `cv.key`.
  #
  # folds:
  #   - {
  #     name: fold1,
  #     train: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  #     test:  [1, 2, 3]
  #   }
  #   - {
  #     name: fold2,
  #     train: [1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  #     test:  [4, 5, 6]
  #   }
  #   - {
  #     name: fold3,
  #     train: [1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  #     test:  [7, 8, 9]
  #   }
  #   - {
  #     name: fold4,
  #     train: [1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  #     test:  [10, 11, 12]
  #   }
  #   - {
  #     name: fold5,
  #     train: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  #     test:  [13, 14, 15]
  #   }
  #   - {
  #     name: fold6,
  #     train: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 19, 20, 21, 22, 23, 24],
  #     test:  [16, 17, 18]
  #   }
  #   - {
  #     name: fold7,
  #     train: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22, 23, 24],
  #     test:  [19, 20, 21]
  #   }
  #   - {
  #     name: fold8,
  #     train: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
  #     test:  [22, 23, 24]
  #   }

  # Alternative notation. Fold indexes are automatically assigned from front to back.
  #
  # folds:
  #   - train: [3, 4, 5, 6]
  #     test: [1]
  #   - train: [1, 2, 5, 6]
  #     test: [3]
  #   - train: [1, 2, 3, 4]
  #     test: [5]

  # In each CV fold, the training samples are removed if they have overlapping 
  # values of `cv exclusive key` with the test samples so that the training and
  # test samples do not have overlapping values for `cv exclusive key`.
  # Set `null` if not specified.
  #
  exclusive_key: category_index
